#! /usr/bin/env python# 异常和捕获# 如果在开发时，遇到这种情况try:    num = int(input('please input num: '))    result = 10 / numexcept:    print('erro')print('---')# 不能确定正常执行的代码# 不能确定正常执行的代码# 不能确定正常执行的代码# 不能确定正常执行的代码# 不能确定正常执行的代码# 不能确定正常执行的代码# 不能确定正常执行的代码# 捕获之后，还可以继续执行# 捕获之后，还可以继续执行# 实际上，后面是可以继续执行的