# 主动抛出异常# 抛出异常对象def input_password():    pwd = input('please input password: ')    div = 10 / pwd    return divdef test_raise():    try:        number = input_password()  # 实际上的用法，还是继承的父类，然后输出的信息    except Exception as err:        raise (Exception('let move'))    print('try is it ok')def main():    test_raise()    print('if i have no i will go on')if __name__ == '__main__':    try:        for i in range(2):            main()    except Exception as err:        raise Exception('hi man, this is type is error!')    for n in range(10):        print(n)# 创建异常对象，主动抛出异常# 创建异常对象，主动